export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_MODAL_EDIT = 'OPEN_MODAL_EDIT';
export const CLOSE_MODAL_EDIT = 'CLOSE_MODAL_EDIT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';